owner: twaslowski
repo: homelab-uptime

sites:
  - name: Vaultwarden
    url: https://warden.twaslowski.com
  - name: paperless-ngx
    url: https://paperless.twaslowski.com
  - name: memos
    url: https://memos.twaslowski.com


status-website:
  baseUrl: /homelab-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: homelab-uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/twaslowski/homelab-uptime
